import type { NodeKindSpec, ShapeId } from './types.ts'

/**
 * Catálogo de tipos de nodo. Cada entrada responde tres preguntas:
 * qué construcción de Python es, por qué se ve así, y **cómo se edita gráficamente**.
 *
 * Reglas del catálogo (verificadas por los tests):
 * - La terna (silueta, trazo, relleno) es única: el tipo se distingue en escala de grises.
 * - Contenedor ⇔ trazo discontinuo y sin relleno.
 * - Todo nodo que no sea un contenedor ofrece un control editable.
 */
const base = { elevation: 'flat', scaleBy: 'none', footprint: { w: 1, h: 1 } } as const

export const NODE_KINDS = [
  // ── Valores: datos puros, hojas del grafo. Editables directamente, sin puerto de entrada. ──
  {
    ...base,
    id: 'value.str',
    name: 'Texto',
    python: '"hola" · f"{x}"',
    role: 'value',
    badge: 'value',
    icon: 'quote',
    shape: 'card',
    stroke: 'solid',
    fill: 'solid',
    control: 'text',
    footprint: { w: 1, h: 0.95 },
    ports: { in: false, out: true },
    why: 'Una tarjeta simple con un campo de texto: no depende de nada, así que no tiene entrada y se escribe directamente.',
  },
  {
    ...base,
    id: 'value.number',
    name: 'Número',
    python: '42 · 3.14',
    role: 'value',
    badge: 'value',
    icon: 'hash',
    shape: 'card-flag',
    stroke: 'solid',
    fill: 'solid',
    control: 'number',
    footprint: { w: 0.95, h: 0.95 },
    ports: { in: false, out: true },
    why: 'Borde izquierdo plano, porque nada entra: el valor se ajusta con un deslizador y un campo, no escribiendo el literal.',
  },
  {
    ...base,
    id: 'value.bool',
    name: 'Booleano',
    python: 'True · False',
    role: 'value',
    badge: 'value',
    icon: 'toggle',
    shape: 'card-toggle',
    stroke: 'solid',
    fill: 'solid',
    control: 'boolean',
    footprint: { w: 0.9, h: 0.9 },
    ports: { in: false, out: true },
    why: 'El lado derecho es la pista de un interruptor: solo hay dos estados posibles, y se cambian con un toque.',
  },
  {
    ...base,
    id: 'value.none',
    name: 'None',
    python: 'None',
    role: 'value',
    badge: 'value',
    icon: 'circle-slash',
    shape: 'card',
    stroke: 'dotted',
    fill: 'ghost',
    control: 'constant',
    footprint: { w: 0.95, h: 0.82 },
    ports: { in: false, out: true },
    why: 'Ausencia de valor: la misma tarjeta de un literal, pero punteada y translúcida, con un desplegable para darle un valor real.',
  },

  // ── Colecciones: datos con estructura. Crecen con la cantidad de elementos. ──
  {
    ...base,
    id: 'data.list',
    name: 'Lista',
    python: '[1, 2, 3] · tuple · set',
    role: 'data',
    badge: 'data',
    icon: 'list',
    shape: 'card-stack',
    stroke: 'solid',
    fill: 'solid',
    control: 'list',
    scaleBy: 'cardinality',
    ports: { in: true, out: true },
    why: 'Capas apiladas: muchos elementos en un objeto. Los elementos son chips que se añaden y se borran uno a uno.',
  },
  {
    ...base,
    id: 'data.dict',
    name: 'Diccionario',
    python: '{"a": 1}',
    role: 'data',
    badge: 'data',
    icon: 'braces',
    shape: 'card-notch',
    stroke: 'solid',
    fill: 'solid',
    control: 'dict',
    scaleBy: 'cardinality',
    footprint: { w: 1.05, h: 1.05 },
    ports: { in: true, out: true },
    why: 'Muescas laterales que separan clave de valor, y filas editables clave → valor en el cuerpo.',
  },
  {
    ...base,
    id: 'data.dataframe',
    name: 'DataFrame',
    python: 'pd.DataFrame(...)',
    role: 'data',
    badge: 'data',
    icon: 'table',
    shape: 'card-grid',
    stroke: 'solid',
    fill: 'solid',
    control: 'table',
    scaleBy: 'cardinality',
    footprint: { w: 1.2, h: 1.15 },
    ports: { in: true, out: true },
    why: 'Barra de título y columnas: la silueta ya es una tabla. Dentro se eligen columnas y se ordena sin tocar el código.',
  },

  // ── Transformaciones: el dato entra y sale distinto. Punta de flecha a la derecha. ──
  {
    ...base,
    id: 'transform.call',
    name: 'Llamada',
    python: 'df.groupby("a") · len(x)',
    role: 'transform',
    badge: 'transform',
    icon: 'function',
    shape: 'card-chevron',
    stroke: 'solid',
    fill: 'solid',
    control: 'args',
    scaleBy: 'ops',
    footprint: { w: 1.05, h: 1 },
    ports: { in: true, out: true },
    why: 'Punta de flecha: el dato entra por la izquierda y sale transformado. Sus argumentos son campos con nombre.',
  },
  {
    ...base,
    id: 'transform.operation',
    name: 'Operación',
    python: 'a + b · x > 3',
    role: 'transform',
    badge: 'transform',
    icon: 'sigma',
    shape: 'pill-chevron',
    stroke: 'solid',
    fill: 'solid',
    control: 'expression',
    footprint: { w: 0.9, h: 0.72 },
    ports: { in: true, out: true },
    why: 'Una píldora con punta: una operación atómica, la unidad más pequeña que transforma. El operador se elige de una lista.',
  },
  {
    ...base,
    id: 'transform.comprehension',
    name: 'Comprensión',
    python: '[x * 2 for x in xs]',
    role: 'transform',
    badge: 'transform',
    icon: 'repeat',
    shape: 'card-loop',
    stroke: 'solid',
    fill: 'solid',
    control: 'expression',
    scaleBy: 'ops',
    footprint: { w: 1.05, h: 1.05 },
    ports: { in: true, out: true },
    why: 'Tarjeta con arco de retorno: la misma transformación aplicada a cada elemento de una secuencia.',
  },
  {
    ...base,
    id: 'transform.lambda',
    name: 'Lambda',
    python: 'lambda x: x + 1',
    role: 'transform',
    badge: 'transform',
    icon: 'lambda',
    shape: 'card-chevron',
    stroke: 'dotted',
    fill: 'ghost',
    control: 'expression',
    footprint: { w: 0.95, h: 0.9 },
    ports: { in: true, out: true },
    why: 'La misma punta de flecha que una llamada, pero punteada y translúcida: la transformación está definida y aún no se ejecuta.',
  },

  // ── Control: el camino se decide, se repite o se corta. ──
  {
    ...base,
    id: 'control.condition',
    name: 'Condición',
    python: 'if x > 3',
    role: 'control',
    badge: 'control',
    icon: 'branch',
    shape: 'card-fork',
    stroke: 'solid',
    fill: 'solid',
    control: 'condition',
    footprint: { w: 1.05, h: 1.05 },
    ports: { in: true, out: true },
    why: 'Dos salidas separadas en el borde derecho (verdadero arriba, falso abajo). La condición se arma con campo, operador y valor.',
  },
  {
    ...base,
    id: 'control.loop',
    name: 'Bucle',
    python: 'for x in xs · while c',
    role: 'control',
    badge: 'control',
    icon: 'loop',
    shape: 'card-tab',
    stroke: 'solid',
    fill: 'solid',
    control: 'loop',
    footprint: { w: 1, h: 1.1 },
    ports: { in: true, out: true },
    why: 'Una pestaña que anuncia lo que se repite; durante la ejecución muestra el progreso de la iteración actual.',
  },
  {
    ...base,
    id: 'control.with',
    name: 'Con',
    python: 'with abre() as f',
    role: 'control',
    badge: 'control',
    icon: 'lock',
    shape: 'card-tab',
    stroke: 'solid',
    fill: 'ghost',
    control: 'with',
    footprint: { w: 1, h: 1.1 },
    ports: { in: true, out: true },
    why: 'Una pestaña como la del bucle, pero sin repetir nada: envuelve lo que ocurre mientras el recurso está abierto, y lo cierra al salir.',
  },
  {
    ...base,
    id: 'control.try',
    name: 'Intentar',
    python: 'try',
    role: 'control',
    badge: 'control',
    icon: 'shield',
    shape: 'card-window',
    stroke: 'solid',
    fill: 'glass',
    control: 'code',
    footprint: { w: 1, h: 1.1 },
    ports: { in: true, out: true },
    why: 'Envuelve lo que se intenta. Sus recuperaciones (si falla, si no falla, al final) van dentro, cada una en su propio marco.',
  },
  {
    ...base,
    id: 'control.except',
    name: 'Si falla',
    python: 'except ValueError as e',
    role: 'control',
    badge: 'control',
    icon: 'x',
    shape: 'card-cut',
    stroke: 'solid',
    fill: 'glass',
    control: 'handler',
    footprint: { w: 1, h: 1.1 },
    ports: { in: true, out: true },
    why: 'La esquina cortada de lo que interrumpe el flujo: solo se recorre cuando algo falla, y dice qué error atrapa.',
  },
  {
    ...base,
    id: 'control.clause',
    name: 'Cláusula',
    python: 'else · finally',
    role: 'control',
    badge: 'control',
    icon: 'check',
    shape: 'card-notch',
    stroke: 'solid',
    fill: 'glass',
    control: 'code',
    footprint: { w: 1, h: 1.1 },
    ports: { in: true, out: true },
    why: 'El otro extremo de un intento: lo que se hace si no falló, o pase lo que pase.',
  },
  {
    ...base,
    id: 'control.break',
    name: 'Salir',
    python: 'break',
    role: 'control',
    badge: 'control',
    icon: 'exit',
    shape: 'card-endcap',
    stroke: 'solid',
    fill: 'glass',
    control: 'code',
    footprint: { w: 0.8, h: 0.75 },
    ports: { in: true, out: false },
    why: 'Extremo plano y cristal: el flujo termina aquí y sale del bucle. Su cable va al puerto de salida del bucle que lo contiene.',
  },
  {
    ...base,
    id: 'control.continue',
    name: 'Siguiente',
    python: 'continue',
    role: 'control',
    badge: 'control',
    icon: 'skip',
    shape: 'card-chevron',
    stroke: 'solid',
    fill: 'glass',
    control: 'code',
    footprint: { w: 0.8, h: 0.75 },
    ports: { in: true, out: false },
    why: 'Punta y cristal: salta el resto de la vuelta. Su cable vuelve a la cabecera del bucle, no al final.',
  },
  {
    ...base,
    id: 'control.raise',
    name: 'Excepción',
    python: 'raise ValueError',
    role: 'control',
    badge: 'control',
    icon: 'alert',
    shape: 'card-cut',
    stroke: 'solid',
    fill: 'solid',
    control: 'signal',
    footprint: { w: 0.95, h: 0.95 },
    ports: { in: true, out: false },
    why: 'Esquina cortada, como una señal de alto: el flujo se detiene y no tiene salida. Se elige el tipo de error y el mensaje.',
  },
  {
    ...base,
    id: 'control.return',
    name: 'Retorno',
    python: 'return total',
    role: 'control',
    badge: 'control',
    icon: 'return',
    shape: 'card-endcap',
    stroke: 'solid',
    fill: 'solid',
    control: 'expression',
    footprint: { w: 0.95, h: 0.88 },
    ports: { in: true, out: false },
    why: 'Extremo derecho plano, el reflejo de un literal: nada sale de aquí hacia el lienzo, el valor sale de la función.',
  },

  // ── Efectos y salida: lo que toca fuera del programa y lo que se mira. ──
  {
    ...base,
    id: 'effect.io',
    name: 'Efecto externo',
    python: 'open(path) · requests.get(url)',
    role: 'effect',
    badge: 'effect',
    icon: 'globe',
    shape: 'card-double',
    stroke: 'solid',
    fill: 'solid',
    control: 'io',
    footprint: { w: 1.1, h: 1.05 },
    ports: { in: true, out: true },
    why: 'Doble contorno: el código sale del programa y toca el mundo (disco, red, procesos). Se edita destino y modo.',
  },
  {
    ...base,
    id: 'output.display',
    name: 'Salida',
    python: 'display(df) · plt.show()',
    role: 'output',
    badge: 'output',
    icon: 'chart',
    shape: 'card-window',
    stroke: 'solid',
    fill: 'solid',
    control: 'stats',
    elevation: 'raised',
    footprint: { w: 1.15, h: 1.6 },
    ports: { in: true, out: false },
    why: 'Una ventana elevada sobre el plano: es un resultado persistente. Dentro vive la vista real del dato, con su propio control de rango.',
  },

  // ── Fronteras: lo ajeno, lo encapsulado y lo que aún no se entiende. ──
  {
    ...base,
    id: 'external.import',
    name: 'Import',
    python: 'import pandas as pd',
    role: 'external',
    badge: 'neutral',
    icon: 'package',
    shape: 'card-notch',
    stroke: 'dotted',
    fill: 'ghost',
    control: 'module',
    footprint: { w: 0.95, h: 0.85 },
    ports: { in: false, out: true },
    why: 'Las muescas de un diccionario, pero punteadas y translúcidas: es un objeto con nombres que viene de fuera del archivo.',
  },
  {
    ...base,
    id: 'abstraction.collapsed',
    name: 'Función',
    python: 'def load_sales(path): ...',
    role: 'abstraction',
    badge: 'neutral',
    icon: 'folder',
    shape: 'card-tab',
    stroke: 'solid',
    fill: 'glass',
    control: 'signature',
    scaleBy: 'ops',
    footprint: { w: 1.05, h: 1.1 },
    ports: { in: true, out: true },
    why: 'Pestaña de vidrio esmerilado: hay complejidad encapsulada detrás. Se editan sus parámetros sin abrirla.',
  },
  {
    ...base,
    id: 'smart.ui',
    name: 'Nodo inteligente',
    python: 'df.query(...) con UI generada',
    role: 'abstraction',
    badge: 'neutral',
    icon: 'sparkles',
    shape: 'card',
    stroke: 'solid',
    fill: 'glass',
    control: 'query',
    footprint: { w: 1.1, h: 1.15 },
    ports: { in: true, out: true },
    why: 'Vidrio con contorno sólido: una interfaz generada y guardada en caché que sustituye al algoritmo por controles.',
  },
  {
    ...base,
    id: 'opaque.code',
    name: 'Código opaco',
    python: 'construcción no soportada',
    role: 'opaque',
    badge: 'neutral',
    icon: 'help',
    shape: 'card-cut',
    stroke: 'dotted',
    fill: 'ghost',
    control: 'code',
    footprint: { w: 1, h: 1 },
    ports: { in: true, out: true },
    why: 'Esquina cortada y trazo punteado: aquí el lienzo se detiene porque Prysel no entiende esto, y muestra el código tal cual.',
  },

  // ── Espacios: territorios que contienen nodos. Discontinuos y sin relleno (regla del DS). ──
  {
    ...base,
    id: 'space.for',
    name: 'Espacio for',
    python: 'for row in rows:',
    role: 'container',
    badge: 'control',
    icon: 'loop',
    shape: 'frame',
    stroke: 'dashed',
    fill: 'none',
    control: 'none',
    ports: { in: true, out: true },
    why: 'Un marco que envuelve todo lo que se repite: el bucle es un territorio, no una caja.',
  },
  {
    ...base,
    id: 'space.if',
    name: 'Espacio if',
    python: 'if / else',
    role: 'container',
    badge: 'control',
    icon: 'branch',
    shape: 'frame-fork',
    stroke: 'dashed',
    fill: 'none',
    control: 'none',
    ports: { in: true, out: true },
    why: 'Dos carriles físicamente separados: la bifurcación es real, no una condición escrita dentro de una caja.',
  },
  {
    ...base,
    id: 'space.try',
    name: 'Espacio try',
    python: 'try / except',
    role: 'container',
    badge: 'control',
    icon: 'shield',
    shape: 'frame-guard',
    stroke: 'dashed',
    fill: 'none',
    control: 'none',
    ports: { in: true, out: true },
    why: 'Un carril principal y, debajo, uno de recuperación que solo se resalta cuando algo falla.',
  },
] as const satisfies readonly NodeKindSpec[]

export type NodeKindId = (typeof NODE_KINDS)[number]['id']

/**
 * Los tipos que envuelven lo que hay dentro: un bucle, un `with`, un `try` y cada una de sus
 * cláusulas. Con cuerpo se dibujan como territorio, como una función, pero sin sus parámetros.
 */
export const TERRITORY_KINDS: ReadonlySet<string> = new Set([
  'control.loop',
  'control.with',
  'control.try',
  'control.except',
  'control.clause',
])

/** ¿Es un tipo que se dibuja como territorio cuando tiene algo dentro? (Las funciones también, aparte.) */
export const isTerritoryKind = (kind: string): boolean => TERRITORY_KINDS.has(kind)

/** Los que llevan un editor en su cabecera (`para x en …`, `con … como …`, `si falla …`). */
export const HEADER_EDITOR_KINDS: ReadonlySet<string> = new Set([
  'control.loop',
  'control.with',
  'control.except',
])

/** La silueta de un territorio: la pestaña de carpeta, sea cual sea el tipo. */
export const territoryShape = (kind: { id: string; shape: ShapeId }): ShapeId =>
  isTerritoryKind(kind.id) ? 'card-tab' : kind.shape

const byId = new Map<string, NodeKindSpec>(NODE_KINDS.map((k) => [k.id, k]))

export function getKind(id: NodeKindId): NodeKindSpec {
  const kind = byId.get(id)
  if (!kind) throw new Error(`Tipo de nodo desconocido: ${id}`)
  return kind
}
